### ISSUE TITLE
Feature Request: On subsequent runs, the script shouldn't generate profiles for cores that it knew it had to rename

### ISSUE THREAD

**Issue by TheJesusFish** [Matt-Retrogamer/mister-rt4k-dv1-profiles-generator#8] opened 2024-10-25 14:27 UTC
For instance, on first run, the script will generate a Turbografyx 16.rt4k (or whatever the core name is) and then rename it to TG16.rt4k at the end. If you run the script again, it will regenerate a new and unnecessary Turbografyx 16.rt4k profile.

**Comment by Matt-Retrogamer** [comment] 2024-10-29 15:03
Thanks for the report, the issue is fixed in https://github.com/Matt-Retrogamer/mister-rt4k-dv1-profiles-generator/commit/c7a4cf7d80dd2f63c9baecd29e449630251c4c48

**Closed by Matt-Retrogamer** 2024-10-29 15:03 UTC
